version: "2.4"
services:
  database:
    image: quay.io/azavea/postgis:2.3-postgres9.6-slim
    volumes:
      - ./data/:/tmp/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pgsockets
      - POSTGRES_PASSWORD=pgsockets
      - POSTGRES_DB=pgsockets
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pgsockets"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s

