version: '3'
services:
    pg-sockets-hs:
        build: .
        image: pg-sockets-hs
        command: pg-sockets-hs
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - pg-sockets-hs
