version: '3'
services:
  postgres:
    image: quay.io/azavea/postgis:2.3-postgres9.6-slim
    command: postgres -c log_statement=all
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - ./data:/opt/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3

  pg-sockets-hs:
    build: .
    image: pg-sockets-hs
    command: pg-sockets-hs
    volumes:
      - ./data:/opt/data
    expose:
      - "1234"

  nginx:
    build: ./nginx
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - pg-sockets-hs
